
from __future__ import annotations
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors


# Optional import for feather support
try:
    import pyarrow as pa
    import pyarrow.ipc as ipc
    FEATHER_AVAILABLE = True
except ImportError:
    FEATHER_AVAILABLE = False
    print("Warning: pyarrow not available. Feather file support disabled.")


colors_dict = {
    'disk':     '#439494',      # Cyan
    'square':   '#bd6034',      # Orange
    'arrow2':   '#6c916c',      # Green
    'star':     '#b64949',      # Red
    'triangle': '#8b8b47',      # Gold
    'annulusBarred':   '#956e6e',      # Brown
    'annulus':  '#975497',      # Magenta
}

# Darker colors for markers
dark_colors_dict = {
    'disk': '#2d6464',      # Dark cyan
    'annulus': '#633663',   # Dark magenta
}


def as_rgb_float(col) -> tuple[float, float, float]:
    """Convert '#rrggbb' or 'tab:blue' → (r,g,b) floats 0-1."""
    return mcolors.to_rgb(col)

def default_colours(n: int):
    """Fallback colour array."""
    return plt.cm.jet(np.linspace(0., 1., n))


############### LOAD DATA FUNCTIONS ###############

def load_data_feather(filename: str):
    """Load data from feather file (simulation format)."""
    if not FEATHER_AVAILABLE:
        raise ImportError("pyarrow is required for feather file support")
    
    with ipc.open_file(filename) as reader:
        schema = reader.schema
        meta = schema.metadata or {}
        decoded_meta = {k.decode(): v.decode() for k, v in meta.items()}

    config = decoded_meta.get("configuration", {})
    df = pd.read_feather(filename)
    return df, config

def load_data_csv(diffusion_csv: str, final_lambdas_csv: str = None):
    """Load CSV data generated by log_parser.py (experimental format)."""
    diffusion_df = pd.read_csv(diffusion_csv)
    
    if final_lambdas_csv is None:
        if 'combined_diffusion_data.csv' in diffusion_csv:
            final_lambdas_csv = diffusion_csv.replace('combined_diffusion_data.csv', 'final_lambdas_summary.csv')
        else:
            base_name = diffusion_csv.replace('_diffusion_data.csv', '')
            final_lambdas_csv = base_name + '_final_lambdas.csv'
    
    try:
        final_lambdas_df = pd.read_csv(final_lambdas_csv)
    except FileNotFoundError:
        print(f"Warning: Final lambdas file {final_lambdas_csv} not found.")
        print("Creating final lambdas from diffusion data...")
        final_lambdas_df = create_final_lambdas_from_diffusion(diffusion_df)
    
    df = merge_diffusion_and_final_lambdas(diffusion_df, final_lambdas_df)
    return df, {}

def create_final_lambdas_from_diffusion(diffusion_df: pd.DataFrame) -> pd.DataFrame:
    """Extract final lambda values from diffusion data if final_lambdas file is missing."""
    final_steps = diffusion_df.groupby(['filename', 'iteration']).apply(
        lambda x: x.loc[x['step'].idxmax()]
    ).reset_index(drop=True)
    
    final_lambdas_df = pd.DataFrame({
        'filename': final_steps['filename'],
        'arena': final_steps['arena'],
        'date': final_steps['date'],
        'robot_id': final_steps['robot_id'],
        'iteration': final_steps['iteration'],
        'final_lambda': final_steps['lambda']
    })
    
    return final_lambdas_df

def merge_diffusion_and_final_lambdas(diffusion_df: pd.DataFrame, final_lambdas_df: pd.DataFrame) -> pd.DataFrame:
    """Merge diffusion and final lambda data to create format expected by plotting functions."""
    plot_df = final_lambdas_df.copy()
    plot_df = plot_df.rename(columns={
        'iteration': 'current_it',
        'final_lambda': 'avg_lambda',
        'arena': 'arena_file'
    })
    
    if 'robot_id' in plot_df.columns:
        plot_df['experiment_id'] = plot_df['filename'].astype(str) + '_' + plot_df['robot_id'].astype(str)
    else:
        plot_df['experiment_id'] = plot_df['filename'].astype(str)
    
    return plot_df


def load_data(input_file: str, final_lambdas_csv: str = None):
    """
    Universal data loader that automatically detects file format.
    
    Parameters
    ----------
    input_file : str
        Path to input file (.feather, .csv, or diffusion CSV)
    final_lambdas_csv : str, optional
        For CSV input: path to final lambdas CSV file
    
    Returns
    -------
    df : DataFrame
        Data with standardized column names for plotting
    config : dict
        Configuration metadata (empty for CSV files)
    """
    
    if input_file.endswith('.feather'):
        print(f"Loading feather file: {input_file}")
        return load_data_feather(input_file)
    
    elif input_file.endswith('.csv'):
        print(f"Loading CSV file: {input_file}")
        return load_data_csv(input_file, final_lambdas_csv)
    
    else:
        # Try to auto-detect based on content/extension
        if os.path.exists(input_file):
            if 'diffusion' in input_file.lower():
                print(f"Auto-detected CSV diffusion file: {input_file}")
                return load_data_csv(input_file, final_lambdas_csv)
            else:
                # Default to feather
                print(f"Auto-detected feather file: {input_file}")
                return load_data_feather(input_file)
        else:
            raise FileNotFoundError(f"Input file not found: {input_file}")

# MODELINE "{{{1
# vim:expandtab:softtabstop=4:shiftwidth=4:fileencoding=utf-8
# vim:foldmethod=marker
